pi-hole/docs

docs/guides/unbound.md

Change suggested unbound documentation as discussed in https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378
Signed-off-by: DL6ER <dl6er@dl6er.de>

Update Pi-hole + unbound guide

---

.travis.yml

Signed-off-by: Adam Warner <adamw@rner.email>

add BOT_NAME and BOT_EMAIL to travis.yml

---

mkdocs.yml

Adjust `site_url`. This will hopefully fix the currently broken 404 page.

Adjust site_url

---

docs/guides/vpn/android-client.md
docs/guides/vpn/clients.md
docs/guides/vpn/firewall.md
docs/guides/vpn/only-dns-via-vpn.md

This should bring the docs pages up to date with where the wiki pages were.

Update VPN docs from last wiki revision

---

docs/guides/vpn/dual-operation.md

Fixes issue number 3 from  #24

Remove extraneous HTML tag from VPN config snippet

---

docs/ftldns/regex.md

Add methods to reload the regex list

---

docs/guides/vpn/installation.md

Specify the IP address to be used for install

---

docs/ftldns/telnet-api.md

pi-hole/FTL#305 changes this output

Update FTL telnet ">version" output

---

docs/ftldns/blockingmode.md
docs/ftldns/configfile.md

Improve wording and re-arrange subsections.

Improve blocking mode page

---

docs/ftldns/regex.md

Also added a third method of just restarting the service.

Fix list formatting in how to reload regex

---

mkdocs.yml

Add GitHub link to top bar

---

docs/ftldns/configfile.md
docs/ftldns/database.md
docs/ftldns/privacylevels.md

- New privacy level 4
- New config parameter `DBIMPORT`

Update FTL documentation

---

docs/abbreviations.md
docs/ftldns/dns-cache.md
mkdocs.yml

This PR is connected to https://github.com/pi-hole/AdminLTE/pull/830

Add DNS cache documentation

---

docs/ftldns/regex/tutorial.md

See https://discourse.pi-hole.net/t/12745

Fix incorrect regex example

---

docs/ftldns/configfile.md

I found that it was missing when looking for it to help a user.

Add the `ANALYZE_ONLY_A_AND_AAAA` config option

---

docs/guides/unbound.md

As discussed in https://discourse.pi-hole.net/t/recommended-improvement-for-unbound-guide/13023

Improve unbound guide

---

docs/guides/whitelist-blacklist.md
mkdocs.yml

Ported this wiki page (https://github.com/pi-hole/pi-hole/wiki/Whitelisting-and-Blacklisting) to Guides section under "Editing Whitelisting and Blacklisting"

Port Whitelisting and Blacklisting Guide from Wiki

---

README.md

I wanted to make the main repo README a little bit more informative and user friendly for others to get started, this is my first go of it.
Signed-off-by: Tom Daykin <tdaykin@live.co.uk>

Updated repo Readme 

---

docs/core/pihole-command.md
docs/main/core-functions.md
mkdocs.yml

Signed-off-by: Adam Warner <adamw@rner.email>
(It must be October)

Port core-functions from wiki

---

README.md

Improve recent README modifications

---

docs/ftldns/blockingmode.md

Signed-off-by: DL6ER <dl6er@dl6er.de>

Add NODATA description

---

docs/ftldns/configfile.md

The maximum value will be changed with FTL v4.2.2. Therefore, do not merge this PR until it is released.
FTL v4.2.2 release PR: pi-hole/FTL#510

Update MAXLOGAGE maximum value

---

docs/guides/dns-over-https.md

Signed-off-by: Chris Weiss <chris.weiss@gmail.com>

Fixing docs for Raspi DoH setup - a few steps require sudo.

---

docs/main/prerequesites.md

Update Fedora support to 28/29.

bump supported Fedora versions

---

docs/main/coverage.md

Signed-off-by: Brian Christner <brian.christner@gmail.com>

Added pi hole coverage article

---

docs/main/prerequesites.md

- Clarification required on supported Ubuntu release and architectures.
- Any other updates
Edit: removed WIP tag

add architectures to support matrix

---

docs/main/prerequesites.md

No changes to meaning, just removing some duplicate words, adding a couple of missing apostrophes, tidying up a couple of sentences.
Signed-off-by: ncguk <ncguk@me.com>

Spelling and grammar corrections

---

docs/ftldns/database.md

Signed-off-by: DL6ER <dl6er@dl6er.de>

Add documentation for finer-grained externally blocked status types

---

docs/guides/upstream-dns-providers.md

Update Cloudflare learn more link

---

README.md

add docker run details

---

docs/guides/unbound.md

See title. This has been discussed internally and was triggered by my Discourse post [here](https://discourse.pi-hole.net/t/anyone-using-knot-resolver/19750/65?u=dl6er).

Unbound guide: Remove min/max bounds for TTL

---

docs/ftldns/configfile.md
docs/ftldns/database.md
docs/ftldns/regex/overview.md

This PR adds documentation changes from v4.2.3 -> 4.3

Pi-hole documentation for v4.3

---

docs/guides/vpn/firewall.md

Signed-off-by: RamSet <ramset@gmail.com>

Optional firewall snippet 

---

docs/guides/benchmark.md
mkdocs.yml

Based on https://discourse.pi-hole.net/t/test-flood-my-own-dns-server/20216/4

Add benchmarking guide

---

docs/main/prerequesites.md

update supported fedora versions

---

docs/guides/dns-over-https.md

Followed this doc on my Pi-Hole running on top of CentOS 7. Everything works just fine the only thing missing was instructions on where to get the CentOS RPM.

Add download location for CentOS/RHEL/Fedora

---

docs/guides/vpn/dual-operation.md

Insert space to prevent inlining image.

---

docs/guides/vpn/android-client.md
docs/guides/vpn/clients.md
docs/guides/vpn/dual-VPN.md
docs/guides/vpn/dual-operation.md
docs/guides/vpn/dynDNS.md
docs/guides/vpn/only-dns-via-vpn.md
docs/guides/vpn/setup-openvpn-server.md

Fix docs refer to OpenVPN files which have moved in newer versions

---

docs/main/prerequesites.md

Added the commands to allow the mentioned ports in ufw to the prerequesites page.

Add ufw commands to the prerequesites page

---

docs/guides/unbound.md

This is untested but it *should* fix the issue:
BTW that's why IMHO there should be some kind of markdown linting set up. I can fix the current codebase later, but only with linting set up we can make sure such issues never happen again

Fix Markdown syntax issues

---

docs/database/gravity/index.md
docs/database/gravity/lists.md
docs/ftldns/regex/overview.md
docs/ftldns/regex/tutorial.md
mkdocs.yml

Documentation updates related to the v5.0 release.

Add documentation for v5.0

---

docs/guides/vpn/dual-operation.md

Revert "Removed obsolete Optional: Dual operation: LAN & VPN at the same time…"

---

requirements.txt

Remove the unused mkdocs-bootswatch package.

---

docs/main/prerequesites.md

Update supported distributions.

---

.gitignore
.markdownlint.json
.travis.yml
README.md
docs/docker/DHCP.md
docs/ftldns/blockingmode.md
docs/ftldns/compile.md
docs/ftldns/regex/tutorial.md
docs/guides/dns-over-https.md
docs/guides/tor/overview.md
docs/guides/tor/using-tor.md
docs/guides/vpn/firewall.md
docs/index.md
docs/main/basic-install.md
package-lock.json
package.json

This requires #197 merged and needs to be tweaked further. I open it as a preview.
TODO:

Add Markdownlint

---

mkdocs.yml

Signed-off-by: Dan Schaper <dan.schaper@pi-hole.net>

Change to Pi-hole colors

---

mkdocs.yml

Revert "Change to Pi-hole colors"

---

mkdocs.yml
requirements.txt

https://squidfunk.github.io/mkdocs-material/plugins/revision-date/
YAML front matter shouldn't be needed anymore.

Add revision date to pages.

---

mkdocs.yml

Signed-off-by: Dan Schaper <dan.schaper@pi-hole.net>

Use `pi-hole` core repo for GitHub stars/forks

---

docs/main/presentations.md
mkdocs.yml

Redirect to main index, remove from navigation sidebar.

Remove presentation support links

---

docs/main/prerequesites.md

word change

---

.github/workflows/build.yml

Also, switch from the env vars to the `with` options
I will try to test this before merging it later.

Update peaceiris/actions-gh-pages to the v3 tag

---

.github/workflows/build.yml

This way the pip cache will be invalidate when we change the Python version.

CI: add a `PYTHON_VERSION` environment variable

---

docs/database/gravity/example.md

I will try to finish #286 when I have some time ASAP, so that we catch the internal 404s before hitting production, although I thought mkdocs would already fail. Apparently it doesn't.

Fix broken links to images

---

.markdownlint.json
docs/guides/whitelist-blacklist.md

https://deploy-preview-318--pihole-docs.netlify.app/guides/whitelist-blacklist/

Remove HTML tables

---

docs/core/pihole-command.md
docs/guides/benchmark.md
docs/guides/vpn/dual-operation.md
docs/guides/vpn/overview.md
docs/guides/whitelist-blacklist.md
docs/main/origins.md
docs/main/prerequesites.md

Signed-off-by: Adam Warner <me@adamwarner.co.uk>

various tweaks

---

docs/extra.css

These don't seem to be needed with the latest mkdocs-material version.

CSS cleanup

---

mkdocs.yml
overrides/partials/footer.html

Signed-off-by: Adam Warner <me@adamwarner.co.uk>

Add netlify link to footer

---

overrides/partials/footer.html

Revert "Update footer.html"

---

docs/ftldns/database.md
docs/ftldns/regex/index.md
docs/main/presentations.md
mkdocs.yml
requirements.txt

Now the redirects are specified in mkdocs.yml
Fixes #271

Add mkdocs-redirects plugin

---

.github/workflows/build.yml
.github/workflows/test.yml

Change when CI runs.

---

docs/guides/unbound.md

Make sure the daemon is stopped and started properly in case its running already.

stop start unbound

---

docs/index.md

Fixes https://github.com/pi-hole/docs/issues/357 by removing the broken Youtube link
Should go together with https://github.com/pi-hole/pi-hole/pull/3678

Remove broken Youtube link

---

docs/main/prerequisites.md

Clarify, that `52 MB free space` requirement is without the databases.

Clarify disk space requirement

---

docs/guides/dns-over-https.md

Signed-off-by: jnozsc <470215+jnozsc@users.noreply.github.com>

dns-over-https: add document for arm64

---

docs/main/projects.md

Signed-off-by: Lukas Wolfsteiner <lukas@wolfsteiner.media>

Append Pi-hole Shortcuts for macOS to list of community projects

---

docs/guides/tor/overview.md

---
Running a TOR relay resource forwarded.
Changed link to the forwarded wepage.
*A detailed list of any …

link changed

---

overrides/partials/footer.html

---
https://github.com/squidfunk/mkdocs-material/commit/52787c6a9c63e34e2ec861a07f7fa11e8e6687d8#diff-a27d1bad64761f00fd0492849f7ffa9d661fe095e02c691196dfc141fbca650d

footer.html: backport upstream changes

---

package-lock.json
package.json

This is an improved version of of markdownlint-cli, see https://github.com/DavidAnson/markdownlint-cli2
---

Switch to markdownlint-cli2

---

docs/database/gravity/groups.md

The documentation for the group section of the domain database (https://docs.pi-hole.net/database/gravity/groups/) has an incorrect label for one of the fields.  The label identified as "comment" in the documentation is "description" in the database.
- [X ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- X] I am willing to help maintain this change if there are issues with it later.
- [X ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
Please make sure you [Sign …

Correct documentation for the group section of the gravity (domain) database.

---

docs/database/gravity/groups.md

closes #415
---
https://github.com/pi-hole/docs/issues/415#issuecomment-721960766
changes 
> `name` | text | No | Mandatory group name
to 
> `name` | text | Yes | Mandatory group name
This P/R is the support.
---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed …

fix group Table name column - Uniqueness enforces should be Yes

---

docs/guides/tor/performance-issues.md
docs/guides/vpn/installation.md
docs/main/coverage.md
docs/main/projects.md

Fix redirects

---

docs/database/gravity/index.md

Add documentation for new gravity.db:adlist#date_updated column

---

docs/abbreviations.md
docs/ftldns/configfile.md

Adds `REFRESH_HOSTNAMES` config item

Pi-hole FTL v5.3.2 documentation

---

docs/core/pihole-command.md

What does this PR aim to accomplish?
This PR adds details about the teleport switch for the admin cli. The core document has had an extra option added.

adding teleport command doc

---

mkdocs.yml

---
In the sidebar, there are two instances of "Tor" [incorrectly being spelled as "TOR".](https://support.torproject.org/about/why-is-it-called-tor/) 
By changing the title in the …

It's Tor, not TOR (Again)

---

docs/ftldns/compile.md

This may also need adding to the Fedora section?

Add libreadline-dev to FTL build page

---

docs/core/pihole-command.md

---
Found that the "update" command in the elaboration was different from the "update" command in the summary table. Testing out both, I found that the summary table version was correct. Submitting this PR to fix the elaboration to match the summary table.
*A detailed description (such …

[DOC]: Minor doc fix on update command

---

docs/core/pihole-command.md
docs/database/ftl.md
docs/ftldns/compile.md
docs/ftldns/configfile.md
docs/regex/approximate.md
docs/regex/overview.md
docs/regex/pi-hole.md
docs/regex/testmode.md
docs/regex/tutorial.md
mkdocs.yml
package.json

Release-related documentation updates:
- Improve regex documentation
- Update possible query types and query status in database documentation 
- Add missing documentation for `EDNS0_ECS` and `MAXNETAG options

Update documentation for FTL v5.6

---

docs/ftldns/configfile.md

---
Add documentation for the new FTL config option `RATE_LIMIT`

Update documentation for FTL v5.7

---

docs/index.md

Trust this is meant to be here too!
---
N/A
N/A
N/A
---
* You must …

Update "alternative support" links as per homepage

---

docs/main/update.md

---
Simply removes an empty placeholder on the "Updating" page.

Remove empty placeholder

---

docs/main/basic-install.md

Signed-off-by: Ashutosh Verma <mail@ashu.io>
---
Let users know of docker install method
Added Method 3 in basic_install
**What documentation changes (if any) are needed to support this …

Added Method 3 to basic_install

---

docs/routers/fritzbox.md

---
---
* You must follow the template instructions. Failure to do so …

very minor spelling fix

---

docs/ftldns/configfile.md

---
Adds missing config documentation. Fixes #515

Update documentation to fix #515

---

package-lock.json
package.json

---
Old dependabot wanted to do this, but it is no longer there. Choosing to manually do it

Update Linkinator to 2.14.0

---

docs/guides/dns/cloudflared.md

Signed-off-by: Sudarsan Reddy <sreddy@cloudflare.com>
---
It updates binary download links pointing to equinox to point to the cloudflared release pages instead. This is because equinox will be shutting down come September (https://equinox.io/blog/shutting-down). 
It moves all relevant links to permanent ones that my team at cloudflare maintains. 
**What documentation changes (if any) …

docs/guides/dns: Updated cloudflared links to point to github instead

---

docs/guides/dns/cloudflared.md

---
---
* You must follow the template instructions. Failure to do so …

Cloudflared: fix link to linux arm binary

---

docs/guides/dns/cloudflared.md

Signed-off-by: XhmikosR <xhmikosr@gmail.com>
---
* move armhf before arm64 since this is still the most common
* fix a comment
* stop renaming the downloaded binary

Cloudflared: minor tweaks

---

.github/workflows/ci.yml

Signed-off-by: XhmikosR <xhmikosr@gmail.com>
---
Everything seems to work fine without wheel, so I'd say we keep the defaults. We can bring this back later if needed.

CI: remove wheel

---

docs/guides/dns/unbound.md

---
Add a small info how to uninstall unbound.
Fixes https://github.com/pi-hole/docs/issues/553

Add unbound uninstallation info

---

docs/main/prerequisites.md

Add Raspbian Bullseye to supported distros

---

docs/ftldns/configfile.md

---
Adds a few so far undocumented FTL config options

Add missing FTL config options

---

mkdocs.yml

---
To fix the infinite redirect for `/main/prerequisites/` caused by [this commit](https://github.com/pi-hole/docs/commit/5f606a16e44eaab86b9b19ef2f8471154209d73b#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2).
*A detailed description (such as a changelog) and …

Fix infinite redirect

---

docs/main/coverage.md

---
Fixes https://github.com/pi-hole/pi-hole/issues/4337

Fix link in coverage

---

docs/ftldns/configfile.md

---
Adds documentation for the new `BLOCK_ICLOUD_PR` config option. https://github.com/pi-hole/FTL/pull/1171

Add `BLOCK_ICLOUD_PR`  config option

---

mkdocs.yml

---
When instant loading is enabled, clicks on all internal links will work without fully reloading the page.
The resulting page is parsed and injected and all event handlers and components are rebound automatically, i.e., the documentation now behaves like a Single Page Application which seems nicer. Additionally, the search index does now survive navigation, which is especially useful for large documentation sites.

Enable instant loading

---

docs/guides/github/contributing.md
docs/guides/github/dco.md
docs/guides/github/how-to-fork-rebase.md
mkdocs.yml

---
Adds info from https://github.com/pi-hole/pi-hole/pull/3178 (https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md) to the docs also.

Add 'How to fork and rebase'

---

docs/extra.css
docs/ftldns/cache_dump.md
mkdocs.yml

Signed-off-by: DL6ER <dl6er@dl6er.de>
---
---
* You must follow the template instructions. Failure …

Add dnsmasq cache dump documentation

---

docs/ftldns/configfile.md

---
Accompanies https://github.com/pi-hole/FTL/pull/1249

Add documentation for resource warnings config options

---

docs/guides/vpn/wireguard/internal.md

---
Fixes this highlighting:
to
---
* You must follow the template instructions. Failure to do so …

Fix code highlighting

---

docs/guides/vpn/wireguard/internal.md

Fixes https://github.com/pi-hole/docs/issues/636

Fix typo in wg guide

---

docs/routers/asus.md
mkdocs.yml

---
Add ASUS router guide. It's basically the link to ASUS's Pi-hole FAQ wrapped in a bit of text.

Add ASUS router guide

---

README.md

---
Docker version was old and out of date (12)
Update to 16

Update README to use the same version of node as the CI

---

docs/database/gravity/recovery.md
mkdocs.yml

---
Documents the recovery options of the gravity database added by https://github.com/pi-hole/pi-hole/pull/4288

Add recover options to gravity documentation

---

docs/ftldns/package_dump.md
mkdocs.yml

---
Adds info about how to use Pi-hole's internal package dump.
Shamelessly stolen from https://discourse.pi-hole.net/t/dns-resolution-fails-intermittently-with-config-error-is-refused-ede-network-error/52528/15?u=yubiuser

FTL internal package dump

---

docs/database/ftl.md

---
Documentation update following https://github.com/pi-hole/FTL/pull/1255

Query database optimization documentation

---

docs/main/faq.md

---
After some changes in AdminLTE, the recommended way to change the memory limit has changed.
This PR fix the text to reflect the changes.
The text was changed.
This is the documentation.

Change instructions to increase PHP memory_limit

---

README.md
docs/database/gravity/recovery.md
docs/main/post-install.md
mkdocs.yml
requirements.txt

This PR updates the documentation reflecting the latest changes in the FTL v5.14.
It combines https://github.com/pi-hole/docs/pull/659, https://github.com/pi-hole/docs/pull/656, https://github.com/pi-hole/docs/pull/645 and https://github.com/pi-hole/docs/pull/655

Release/ftl v5.14

---

docs/main/faq.md

Signed-off-by: Paul Close <pdclose@gmail.com>
---
Fixes a typo in the FAQ ("availabe" should be "available")
Corrects the typo.
*A detailed …

Fix typo in FAQ

---

docs/database/gravity/groups.md

no -> zero

---

.codespellignore
.github/workflows/codespell.yml
docs/database/gravity/recovery.md
docs/ftldns/configfile.md
docs/ftldns/dnsmasq_warn.md
docs/guides/vpn/openvpn/client.ovpn
docs/main/faq.md
docs/main/prerequisites.md
docs/routers/fritzbox.md

Add code-spell action

---

docs/guides/vpn/openvpn/installation.md

---
[git.io is soon to be deprecated](https://github.blog/changelog/2022-04-25-git-io-deprecation/) and as such the link has been updated. Nyr has also made a similar change in the [repo for this script](https://github.com/Nyr/openvpn-install/commit/36f1d82cbaf566a5de08a0792e7f04104f4914c7#)
The change updates the …

Replace git.io

---

mkdocs.yml

---
---
* You must follow the template instructions. Failure to do so will result in your pull …

Change Copyright year to 2022 in mkdocs.yml

---

mkdocs.yml
overrides/main.html
overrides/partials/copyright.html

Update entity name, remove unneeded year(s).

Update copyright attribution line

---

docs/main/prerequisites.md

---
This PR updates the documentation to be in accordance with the changes introduced by https://github.com/pi-hole/pi-hole/commit/444526ad582818b03263dabc8a01c6fbee5018a4.
Updates the supported OS table.
None.
---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect …

Update supported versions for CentOS and CentOS Stream

---

docs/database/ftl.md

---
Update query table name to reflect changes in [pi-hole/FTL](https://github.com/pi-hole/FTL/commit/beae1b3bf5681156e3ed5f2468c0208145312715).
Update query table name from `queries_storage` to `query_storage`.
This PR updates database/ftl documentation.
---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that …

Update query table name

---

.github/dependabot.yml

Same as https://github.com/pi-hole/AdminLTE/pull/2224

Add docs-maintainers as reviewers to dependebot PRs

---

docs/ftldns/telnet-api.md

Replace item list with headings in Telnet-API documentation. 
See https://github.com/pi-hole/docs/pull/727#pullrequestreview-1012741233
--- …

Change to heading style for API documentation

---

docs/ftldns/configfile.md
docs/ftldns/in-depth.md
docs/regex/overview.md

---
Change FTL's default log file path from `/var/log/pihole/pihole-FTL.log` to `/var/log/pihole/FTL.log`
Change documentation
- **What documentation changes (if any) are needed to support this PR?:**
This *is* the documentation change
---
**By submitting this pull …

Change FTL's default log file path from /var/log/pihole/pihole-FTL.log to /var/log/pihole/FTL.log

---

docs/main/faq.md

---
Documentation part of https://github.com/pi-hole/pi-hole/pull/4747
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base …

Change lighttpd log file names

---

docs/ftldns/telnet-api.md

Documentation for https://github.com/pi-hole/FTL/pull/1355

Add interfaces API endpoint documentation

---

docs/ftldns/telnet-api.md

---
- Fix code block;
- Improve readability.
Remove the extra space and change the complex paragraph into a list.
\-
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to …

Fix + improve telnetapi.md

---

docs/ftldns/dnsmasq_warn.md

Signed-off-by: JeremyStarTM <jeremystartm@staropensource.ddns.net>
---
Fixing a typo
Removed one `S` (changing `ADDRESSS` to `ADDRESS`
- **What documentation changes (if any) are needed to support this PR?:**
None
--- …

Changed "ADDRESSS" to "ADDRESS"

---

mkdocs.yml

This PR fixes the visual error saw in #758
Note:
see discussion in #759
Adding a missing configuration option.
- **What documentation changes (if any) are needed to support this PR?:**
None
--- …

Fixing Tabs config

---

.github/workflows/codespell.yml
docs/regex/pi-hole.md

Ignore some files, also benefitial ==> beneficial

---

docs/main/prerequisites.md

Add link to The Pi Hut's kit

---

docs/core/pihole-command.md
docs/ftldns/blockingmode.md
docs/guides/webserver/nginx.md

---
---
I have deleted references to the block page in the blocking mode explanation page.

Remove mentions of blockpage

---

docs/core/pihole-command.md

We removed the email function (https://github.com/pi-hole/pi-hole/pull/4870), so the docs should reflect this.
--- …

Remove traces of email

---

docs/ftldns/blockingmode.md

This commit includes a gentle rewrite of the "Blocking Mode" docs page.
It reorders, expands, and clarifies each section with more detail about
the blocking modes that currently exist. It also includes an attempt to
standardizes/unifies each section's explanation to be more consistent
and clear.
Signed-off-by: Osman <osman@surkatty.org>
---
This commit is a gentle rewrite of the "[Blocking Mode](https://docs.pi-hole.net/ftldns/blockingmode/)" docs page.
It reorders, expands, and clarifies each section with more detail about
the blocking modes that currently exist. It also includes an attempt to
standardizes/unifies each section's explanation to be more consistent
and clear.
I went through the page …

Refactor and clarify "Blocking mode" page

---

docs/guides/vpn/wireguard/route-everything.md

---
We have seen a few hard-to-debug cases recently where users missed that they need to setup NAT for the route-everything to work as they failed to realize that the second step (tunnel everything) does not work without the former step (access to internal devices). Try to make the hint clearer and give hints …

Slight update to Wireguard documentation

---

.github/workflows/ci.yml

Upgrades the python version in your CI workflow to 3.11. This is supported by mkdocs since the latest upgrade (https://github.com/pi-hole/docs/pull/799)
--- …

Upgrade PYTHON_VERSION to 3.11

---

docs/ftldns/compile.md

Update FTL "Compile from source" page

---

docs/database/ftl.md

Add stale cache query status

---

docs/main/prerequisites.md

Documentation change for https://github.com/pi-hole/pi-hole/pull/4984
---
---

Add CentOS 9 to supported OS

---

docs/guides/dns/unbound.md

Update a word to use plural.
Signed-off-by: Emer <emerconn7@gmail.com>
4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our …

grammatical fix

---

docs/routers/fritzbox-de.md

Fix a few typos in the fritzbox-de
4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation …

Fix typos in fritzbox-de.md

---

docs/main/prerequisites.md

Remove irrelevant information
---
---

Remove note about dhcpcd5, which has not been relevant for a year now.

---

docs/guides/vpn/wireguard/client.md

Improve wireguard guide

---

docs/ftldns/blockingmode.md
docs/ftldns/configfile.md
docs/ftldns/valgrind.md
docs/guides/dns/cloudflared.md
docs/guides/misc/tor/dnssec.md
docs/guides/misc/tor/performance-issues.md
docs/guides/misc/tor/setup.md
docs/guides/misc/tor/using-tor.md
docs/guides/webserver/caddy.md
docs/routers/fritzbox-de.md
docs/routers/fritzbox.md
docs/routers/ubiquiti-usg.md

Fix style of admonitions. See: https://squidfunk.github.io/mkdocs-material/reference/admonitions/
---
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-wit …

Fix admonitions

---

docs/routers/fritzbox-de.md

Adds German translation title.
---
6. I have checked that another pull request for …

Add warning title

---

docs/main/prerequisites.md

Continues on from https://github.com/pi-hole/docs/pull/816, in which I entirely missed this section of the documentation. 
--- …

Clarify static IP information around dhcpcd5

---

docs/ftldns/configfile.md

Fixes a small visual bug.
Add a space.
--- …

Fix info field

---

.github/workflows/stale_pr.yml

Label for issus/PRs should be uniformly written across repos. After changing labels (https://github.com/pi-hole/docs/issues/labels), the workflows need adjustment to reflect the changes.
---
5. I have squashed any …

Change labels in workflows

---

docs/main/prerequisites.md

update prerequisites to add Fedora 37 support
https://github.com/pi-hole/pi-hole/pull/5067
--- …

update prerequisites to add Fedora 37 support

---

docs/main/prerequisites.md

In conjunction with https://github.com/pi-hole/pi-hole/pull/5122

Remove Fedora 35

---

docs/main/projects.md

Signed-off-by: Joseph Carmosino <65987360+josephistired@users.noreply.github.com>
This PR adds my project to the Community Projects page. 
I am excited to introduce my bot that utilizes the Pi-hole API to provide users with an easy and convenient way to manage their Pi-hole server through Discord. The bot allows users to view statistics about their server, such as the number of domains being blocked and the number of DNS queries to date. Additionally, users can easily disable and enable their Pi-hole server with simple commands. See, below for example of commands.
N/A
---
1. I …

Add Discord Pi-hole Bot to community projects

---

docs/routers/tp-link.md
mkdocs.yml

Adds link to TP-Link router FAQ. 
Fixes https://github.com/pi-hole/docs/issues/853
--- …

Add TP-Link router setup

---

docs/guides/dns/cloudflared.md

Please look at the comments below to help us consider your Pull Request.
We are all volunteers, and completing the process outlined will help us review your commits quicker.
1. Base your code and PRs against the repository developmental branch.
---
**What does this …

dns/cloudflared: add warning to add shebang in bash file

---

docs/guides/dns/cloudflared.md

Remove the automatic cloudflared

---

docs/guides/misc/tor/dnssec.md

I'm the author of https://dnssec.vs.uni-due.de. The site is down, but I've relaunched the DNSSEC test at https://wander.science/projects/dns/dnssec-resolver-test/
---
Working link in documentation to DNSSEC test page.
Replaced link.
none.
---
3. I am willing to help maintain this …

Update dnssec.md: replaced link

---

docs/routers/tp-link.md

Missed a letter. Added a word for sentence flow.
4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation …

Update tp-link.md, spelling fix

---

docs/guides/dns/unbound.md

Amends https://github.com/pi-hole/docs/pull/859

Add forgotten restart command to unbound documentation

---

docs/main/prerequisites.md

Add Ubuntu 23 to supported OS

---

docs/main/prerequisites.md

Add Fedora 38 as supported OS

---

docs/main/prerequisites.md

Add Debian 12 as supported OS

---

docs/guides/dns/upstream-dns-providers.md

Add OpenDNS Family Shield IPv6 addresses

---

docs/ftldns/compile.md

Add caution against updating

---

docs/database/gravity/groups.md
docs/database/gravity/index.md

Adjust references to "Adlist"

---

.github/workflows/ci.yml
docs/routers/ubiquiti-usg.md

Same as https://github.com/pi-hole/docs/pull/947, but for current master.
---
6. I …

Update Node to 20

---

docs/main/origins.md

~~Fix the broken links. Jacob took his personal homepage down - I changed the link to point to the internet archive snapshot.~~
~~Open for discussion: as he took the page down, maybe we should honor this and remove the link entirly.~~
See comment below
--- …

Jacobs homepage is down - remove the outdated paragraph

---

docs/api/auth.md

Fix the location of the API. It's not `pi.hole/admin/api` but only `pi.hole/api`

Correct API location

---

.github/dependabot.yml

Removes duplicate lines in `dependabot.yml`
---
6. I have checked that another pull …

Fix dependabot workflow

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/post-create.sh
package-lock.json
package.json

Add devcontainer

---

docs/main/prerequisites.md

Update prerequisites.md to match supported Fedora versions

---

docs/guides/vpn/openvpn/android-client.md
docs/guides/vpn/openvpn/clients.md
docs/guides/vpn/openvpn/deprecation_notice.md
docs/guides/vpn/openvpn/dual-VPN.md
docs/guides/vpn/openvpn/dual-operation.md
docs/guides/vpn/openvpn/dynDNS.md
docs/guides/vpn/openvpn/firewall.md
docs/guides/vpn/openvpn/installation.md
docs/guides/vpn/openvpn/only-dns-via-vpn.md
docs/guides/vpn/openvpn/overview.md
docs/guides/vpn/openvpn/setup-openvpn-server.md
docs/guides/vpn/openvpn/troubleshooting.md
mkdocs.yml

Cherry-picked https://github.com/pi-hole/docs/pull/960 to port to v6
---
6. I have …

Add deprecation notice to OpenVPN pages [v6]

---

docs/main/prerequisites.md

Pihole now supports Fedora 39 and 40 but in documentation it has 38/39 version as supported OS version which creates confusion.
4. File a pull request for any change that requires changes to [our …

Updated supported fedora versions

---

docs/main/prerequisites.md

Add Ubuntu 24 to supported OS list - added by https://github.com/pi-hole/dns-sync/pull/153
---
6. I have checked that another …

Add Ubuntu 24 to supported OS list

---

mkdocs.yml

Adds a small Copy (to clipboard) button to the code blocks
---
6. I have checked that …

Add Copy button to code blocks

---

docs/main/prerequisites.md

Remove CentOS8 from supported OS
---
6. I have checked that another pull request for …

Remove CentOS8 from supported OS

---

docs/regex/pi-hole.md

Typo - tine -> tune

---

docs/main/prerequisites.md

Remove Debian 10 from supported OS as it has not had Debian Security Support since since 10 Sep 2022

---

docs/database/ftl.md
docs/ftldns/debugging.md

See title, accompanies https://github.com/pi-hole/FTL/pull/2062
**Related issue or feature (if applicable):** [N/A](https://github.com/pi-hole/FTL/pull/2062)
---
5. I have squashed any …

Add new QUERY_EXTERNAL_BLOCKED_EDE15 query status

---

docs/guides/dns/cloudflared.md

Fix grammar in `cloudflared` docs

---

docs/docker/configuration.md
docs/docker/upgrading/v5-v6.md

Add note on docker env var configuration regarding custom dnsmasq config files

Add note on Custom dnsmasq config files for Docker installations

---

docs/routers/asus.md

Add a reminder for conditional forwarding + WAN DNS on ASUS router guide

---

docs/ftldns/signals.md

Remove absolute signal numbers as they may be incorrect on some systems. Users should always use the relative signals x with the suggested kill command using `SIGRTMIN+x`:
---
--- …

Tweak FTL signal documentation

---

docs/docker/index.md

Brings the docker compose example file in line with https://github.com/pi-hole/docker-pi-hole?tab=readme-ov-file#quick-start
Fixes https://github.com/pi-hole/docker-pi-hole/issues/1740 …

Update docker compose example

---

docs/main/contact.md

There is Twitter no more. Now is X.

Twitter ==> X

---

docs/docker/index.md

Ports https://github.com/pi-hole/docker-pi-hole/pull/1768 into `docs`
6. I have …

Add NTPport to docker compose example file

---

docs/guides/vpn/openvpn/deprecation_notice.md

OpenVPN: typo fix

---

.github/workflows/ci.yml

CI: switch to Node.js 22 LTS

---

docs/api/auth.md

Fix "JavaScript" case

---

docs/main/pihole-command.md

Pihole command: add enable too

---

docs/docker/upgrading/v5-v6.md

Title - WEBPASSWORD_FILE has since been reintroduced
---
---

WEBPASSWORD_FILE was added back in

---

docs/ftldns/dns-cache.md
mkdocs.yml

Re-add missing dns-cache.md from https://github.com/pi-hole/docs/blob/1a5de9b086b50767ff8f5e43cb58ebeddce482d6/docs/ftldns/dns-cache.md and update/extend it for Pi-hole v6.0.
----
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/docs/issues/1191
---
4. …

Reintroduce DNS cache documentation

---

docs/main/origins.md

Add civetweb to origins.md

---

docs/docker/configuration.md

Fix the issue reported on Discourse:
https://discourse.pi-hole.net/t/v6-on-docker-ftlconf-webserver-api-password-support-secrets/76150/17
See the title
--- …

WEBPASSWORD_FILE must be written using uppercase

---

docs/docker/upgrading/index.md
docs/main/update.md

Read the changelog when updating

---

mkdocs.yml

Fixes the two build info messages.
```
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
- abbreviations.md
- guides/vpn/openvpn/deprecation_notice.md
```
The mkdocs config should probably be tweaked later to warn so that it's stricter.
---
3. …

Add files that aren't supposed to be built in `not_in_nav`

---

docs/main/update.md

Noticed a tiny spelling mistake/typo in docs/main/update.
I hope I've done my pull request correctly, I'm still new at it :)
Hope you're having a great day <3
4. File a pull request for any …

Fix tiny spelling mistake/typo

---

docs/regex/tutorial.md

Fix minor typos in tutorial doc
Hopefully self-explanatory!
N/A
---
5. I have squashed any insignificant commits. …

Fix rogue brackets in regex tutorial

---

docs/main/prerequisites.md

Cleanup firewalled after removal of api port

---

docs/docker/index.md

Fix #1247
Fixing the broken link
---
6. I …

Fix FTLDNS link in docker page

---

docs/guides/vpn/wireguard/server.md

Small Fixes on the `guides/vpn/wireguard/server/` Page

---

docs/main/prerequisites.md

Accompanying https://github.com/pi-hole/pi-hole/pull/6206 
Removes the OS check hint
---
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html …

Remove os check hint

---

docs/guides/dns/upstream-dns-providers.md

Remove documentation reference to DNS.WATCH in line with https://github.com/pi-hole/FTL/pull/2411
---
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-wit …

Documentation change to reflect removal of DNS.WATCH (FTL PR #2411)

---

docs/ftldns/webserver.md
mkdocs.yml

See title. This is mostly a copy-paste PR from https://github.com/pi-hole/FTL/pull/2535.
---
---
5. I have squashed any insignificant commits. …

Add webserver documentation

---

docs/guides/dns/unbound.md

Fixed confusing language that included a double negative

---

docs/docker/tips-and-tricks.md
mkdocs.yml

This moves the docker Tips & Tricks from the docker repo to docs
Only affects the following:
- Disable systemd-resolved port 53
- Set pi-hole as system DNS server
ref: https://github.com/pi-hole/docker-pi-hole/pull/1860
This adds a new .md file named "Tips and Tricks" to which the points mentioned above (e.g., disabling systemd-resolved port 53) have been added.
The text content is almost identical to the one in the Docker repo (readme.md), but has been adapted with formatting improvements and bug fixes so that one of the commands for disabling systemd-resolved port 53 also works under Fedora.
---
1. I have read and understood the …

move docker Tips & Tricks from docker repo to docs

---

docs/guides/dns/unbound.md

Update unbound.md to include more information about the DNSSEC validation flags.
4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at …

Update unbound.md DNSSEC Validation

---

docs/docker/upgrading/index.md
docs/main/pihole-command.md

Follow up of https://github.com/pi-hole/pi-hole/pull/5887
---
6. I have checked that another pull request for this purpose does …

Remove old "reconfigure" option
