docs/guides/vpn/android-client.md

Fix markdown of "guides/vpn/android-client"

---

docs/main/prerequesites.md

Update requirements to only use port 4711 on localhost instead of the port range.

FTL on 4711 only, port no longer increments.

---

docs/index.md

Removes the red text as v4.0 has been officially released

Remove "Pi-hole v4.0 is currently under development"

---

docs/ftldns/configfile.md

This setting was replaced with privacy levels when FTLDNS was added.

Remove QUERY_DISPLAY

---

docs/ftldns/regex/index.html

The web interface links to `/ftldns/regex/` instead of `/ftldns/regex/overview`, and this change will make it easier to change structure without making bad links.

Add redirect for /ftldns/regex/ to overview.html

---

mkdocs.yml

Remove "for v4.0+" part in the header as this is now the regular version of Pi-hole.

Remove "for v4.0+"

---

docs/ftldns/database.md

As we utilize the Online backup functionality of SQLite3, a backup can be generated without having to stop/restart pihole-FTL, i.e., without interruption of DNS service.
Fixes https://github.com/pi-hole/FTL/issues/392

Add backup instructions for long-term database

---

docs/guides/nginx-configuration.md
mkdocs.yml

Brought this page : https://github.com/pi-hole/pi-hole/wiki/Nginx-Configuration over to be stored on the main docs site.
It's listed under the sites "Guides" section. Ran through the local `mkdocs serv` command to check compatibility.
Signed-off-by: Toakan <tdaykin@live.co.uk>

Port NGINX Configuration page from Wiki

---

docs/guides/caddy-configuration.md
mkdocs.yml

Brought this page : https://github.com/pi-hole/pi-hole/wiki/Caddy-Webserver-Frontend over to be stored on the main docs site.
It's listed under the sites "Guides" section. Ran through the local mkdocs serv command to check compatibility.
Signed-off-by: Toakan <tdaykin@live.co.uk>

Port Caddy Configuration page from Wiki

---

docs/guides/upstream-dns-providers.md
mkdocs.yml

Ported this wiki page (https://github.com/pi-hole/pi-hole/wiki/Upstream-DNS-Providers) to the Guides section under "Upstream DNS Providers"

Port Upstream DNS Providers Guide from Wiki

---

docs/ftldns/privacylevels.md

See title. I've also seen that we already have v4.1 features documented although this version is still not released, so I added a comment about level 4 being only available as of v4.1 and higher.

Clarify that regex blocking is not available at privacy level 4

---

requirements.txt

In PyYAML before 4.1, the yaml.load() API could execute arbitrary code. In other words, yaml.safe_load is not used.

Fix for CVE-2017-18342

---

docs/ftldns/regex/index.html
docs/ftldns/regex/index.md

https://github.com/pi-hole/docs/pull/76#pullrequestreview-191988229
Since a subsection can not have an associated page we have to use the folder directory and implicit index.md to index.html generation. The page /ftldns/regex/ will never show in the docs.pi-hole.net as a link, but there are other pages and sites that refer to this URL from when it was a page and not a subsection. 
This PR makes sure that calls to the old URL are redirected to the overview page.

Redirect /ftldns/regex/ to overview page using meta package.

---

docs/ftldns/configfile.md

See title, this only restructures the corresponding page. No additional content is added.

Restructure FTLDNS->Configuration page to list keys in sections

---

docs/extra.css
docs/ftldns/configfile.md

The links use a new `anchor` CSS class attached to an invisible `div`. The class makes sure that the config option is not covered by the header when you go to its link.
CSS class sourced from https://css-tricks.com/hash-tag-links-padding/#article-header-id-1

Fix broken FTLDNS config links

---

docs/extra.css
docs/ftldns/configfile.md

Change UL items to h4 headers and add metadata to set permanent anchor points with TOC callouts.

Permalink anchors and TOC entries for /FTL/configurations/

---

docs/guides/traefik-configuration-nodocker.md
mkdocs.yml

This is a guide on how to set up traefik as an external SSL Termination point for a domain to serve the pihole interface.

add traefik without docker guide

---

docs/ftldns/compile.md

Add required packages for compiling locally on Fedora.
This will probably also work CentOS when using `yum` instead of `dnf`.
Preview:

Add required packages for compiling FTL locally on Fedora

---

docs/guides/nginx-configuration.md

This [adds the `$serverName` to the list of `$authorizedHosts`](https://github.com/pi-hole/pi-hole/blob/master/advanced/index.php#L26-L31) allowed to see the splash page, and should be equivalent to `setenv.add-environment = ("fqdn" => "true")` in lighttpd as [suggested in the Discourse FAQs](https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771). Without this, you could still visit `/admin` directly, but `/` (or any other page if `error_page 404 /pihole/index.php` is added as suggested below) would show [`[ERROR]: Unable to parse results from queryads.php: Unhandled error message ()`](https://github.com/pi-hole/pi-hole/issues/2195).

Add `fastcgi_param FQDN true;` to nginx config

---

docs/guides/unbound.md

guides: unbound: Fix conf file comment grammar

---

requirements.txt

The CI now uses python 3.6 and errors out when trying to install futures. I tested, and it works fine on python 3.6 when the library is removed (previously it was on python 2).

Fix the CI build by removing the futures package

---

docs/index.md

We no longer have access to the old coinbase address. New Coinbase Commerce address added. Removed UnixStickers as it's no longer used.

Update cryptocoin address

---

docs/ftldns/configfile.md

The `GRAVITYDB` sections is commented as we will support this only from v5.0 on.

Add missing config options supported by pihole-FTL

---

docs/guides/upstream-dns-providers.md

It has not been an option in the installer for some time.

Remove FamilyShield DNS

---

docs/guides/nginx-configuration.md

The code highlighting was off on this page, this corrects it. Tested locally

Fixed code highlighting on NGINX guide page

---

docs/core/pihole-command.md
docs/guides/tor/performance-issues.md
docs/guides/vpn/firewall.md

Fixes   #169 
3 broken links:
- **docs/core/pihole-command.md** has a link "/opt/pihole/gravity.sh" which points to the wrong directory.
- **docs/guides/tor/performance-issues.md** has a link "specific country" which points to a blog that has been moved to a new page.
- **docs/guides/vpn/firewall.md** has a link "this page" which points to a page that no longer exists (per [this thread](https://www.reddit.com/r/pihole/comments/b0o0rv/what_happened_to_the_page_on_piholes_website/)). 
- I figured that since this test page no longer exists, the entire sentence pointing to it can be removed.

Fix broken links

---

docs/guides/dns-over-https.md

Custom services should be stored under `/etc/systemd/system/`. I also added syntax highlighting.

DoH guide: Change custom service to be stored under /etc/systemd/system

---

docs/guides/vpn/setup-openvpn-server.md

In February 2019, OpenVPNv2.4 changed the structure they use for `systemd` services. Instead of using the service named `openvpn.service`, it's now templated. For the purposes of the VPN setup guide, the correct service to target is `openvpn-server@server.service`.
The road warrior install script was ported to target this new service in June 2019. [See here for the commit where this was changed.](https://github.com/Nyr/openvpn-install/commit/a46a23d84a4b007dc8f6e964219331f876a21602#diff-cda9722285f1718b319bb88e134e9efeR354)
The outdated reload snippet in the guide will **not** properly load in any edits made to `server.conf`. This causes a confusing bug that allows the use of the VPN under normal circumstances, but seemingly with outdated configuration. The user who's most likely affected …

Update restart target to match OpenVPNv2.4 service

---

README.md
docs/index.md

Note that since GitHub strips `style` etc for security reasons, we need to use the obsolete `align` attribute in README.md.

docs/index.md: switch to the SVG image.

---

mkdocs.yml
requirements.txt

Reverts pi-hole/docs#244
Plugin only added date of last build and not date of last modification to the page.

Revert "Add revision date to pages."

---

requirements.txt

mkdocs-material 4.6.3 no longer needs `mkdocs-minify-plugin` as dependency.

Remove optional dependency from requirements.txt

---

docs/main/prerequesites.md

As discussed here https://discourse.pi-hole.net/t/tips-about-installation-guide/28673 I wrote this pull request to improve the security of the projec and to make this guide consistent with the rules that pihole add to the firewall configuration during the installation.
May be a good idea modify the rule that pihole insert in the fw configuration as I wrote in the pull request.
At the moment I wrote the rules only for iptables and ip6tables because I'm not able to use nor FirewallD nor ufw.

Better security policies in documentation

---

mkdocs.yml
requirements.txt

WIP until v5.0.0 final is out and also we agree on some of the new changes
Not sure if we should keep the default theme icon for the repo; I kept what v4 was using.
Also, I'm not 100% sure if we should enable instant loading; I'll need to test it a little bit more
Preview: <https://deploy-preview-275--pihole-docs.netlify.com/>

Update mkdocs-material to v5.1.0

---

docs/guides/upstream-dns-providers.md

Added info on 1.1.1.1 for Families, including a blog link to explain the service.
Initially using the blog post link, but more info on 1.1.1.1 for Families might make better sense to point to here to make Cloudflare links more uniform: https://cloudflare-dns.com/family/

Add information on 1.1.1.1 for Families

---

docs/main/prerequesites.md

I'm fixing my mistake on the previous pull request
DHCP port is 67 **udp protocol**, so I delete the tcp rule. It was useless.
DHCP must assign the IP address, so we can't check the IP address of the source. If we do so, it simply will not work.

Revisioning DHCP port

---

.github/workflows/test.yml

The latest `actions/setup-node` prints this info by default

CI: remove no longer needed steps

---

README.md
docs/ftldns/compile.md
docs/ftldns/dns-resolver.md
docs/ftldns/in-depth.md
docs/ftldns/privacylevels.md

- Update `libnettle` version (v3.6 released 2020-04-29)
> Nettle is a cryptographic library that is designed to fit easily in more or less any context: In crypto toolkits for object-oriented languages (C++, Python, Pike, ...), in applications like LSH or GNUPG, or even in kernel space. 
- Remove outdated section about `gravity.list`
- Remove privacy level 4 as blocking does not work in this mode (we will remove it for v5.1). No harm to remove the documentation already now. Disabling any processing effectively disables blocking which is counterproductive.
- Removal of hard-coded cache size limit has been removed upstream in dnsmasq v2.81, so remove this comment

General tweaks

---

docs/guides/nginx-configuration.md

- The PHP SQLite module package is named `-sqlite3` on all supported APT-based distros:
- https://packages.debian.org/php-sqlite
- https://packages.ubuntu.com/php-sqlite
- PHP intl is required for Pi-hole v5.
- PHP zip module is not required for Pi-hole, but the xml module is.
- The webserver user requires R/W access to gravity.db since Pi-hole v5.
Signed-off-by: MichaIng <micha@dietpi.com>

Update Nginx config for Pi-hole v5

---

docs/main/prerequesites.md

Update supported versions:
- Fedora: 31 & 32
- CentOS: 7 & 8

Update supported versions for Fedora & CentOS

---

docs/guides/nginx-configuration.md

According to the https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L250 seems that php7.3-cgi is missing.
Found in this ticket https://github.com/pi-hole/pi-hole/issues/3356

added php7.3-cgi

---

docs/main/prerequisites.md

Raspbian was officially renamed to  Raspberry Pi OS.
This PR reflects this by changing the name in "supported OS" table

Rename Raspbian to Raspberry Pi OS in supported OS

---

README.md

Use a current version of Python, node 12 included. 
Run CI and tests, serve after tests pass. 
This isn't the cleanest or the best but it's functional and the previous instructions didn't do all that much. Hopefully this helps.

Update docker instructions.

---

docs/guides/dns-over-https.md

Adds a section to the DNS-Over-HTTPS guide with instructions for how to ensure the cloudflared daemon is kept up-to-date.
This adds update instructions for cloudflared, which handles one part of issue #175

Add instuctions for updating cloudflared binary.

---

docs/guides/unbound.md

That's all this does. Self-applied invalid label, but still needs a merge

Fix spelling mistake noticed after an invalid hacktoberfest PR

---

docs/guides/unbound.md

---
This PR fixes syntax highlighting of unbound configuration. Currently both configuration blocks look like commented out. 
https://docs.pi-hole.net/guides/unbound/#configure-unbound:
https://docs.pi-hole.net/guides/unbound/#add-logging-to-unbound:
Unbound configuration seems to be a YAML file. I'm changing code block language from `ini` to `yaml`. 
**What documentation changes (if …

Syntax highlighting in unbound config

---

docs/guides/vpn/firewall.md
docs/guides/vpn/installation.md

---
Better explain that you need to port forward your vpn. Also, another thing I didn't include in this PR but would be nice to include is a disclaimer that in newer linux dists you need to use iptables-legacy instead of iptables (iptables by itself uses nf tables spits out error messages left and right). When I was setting up …

Explain to noobs that you need to port forward vpn, and make a disclaimer on iptables-legacy

---

docs/main/prerequisites.md

We only use 4711, there is no more autoranging for the telnet API.
---
Remove the port ranges for the telnet API.

Remove FTL's API port range

---

docs/guides/unbound.md

The `unbound` package can come with a systemd service called `unbound-resolvconf.service` and default enabled (Pi-OS Buster at least).
It instructs `resolvconf` to write `unbound`'s own DNS service at `nameserver 127.0.0.1` , but without the 5335 port, into the file `/etc/resolv.conf`.
These added instructions allow one to use the DNS servers configured in `dhcpcd.conf` instead of the one pushed by the `unbound-resolvconf` service.
- [X ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X ] I have made only one major change in my proposed changes.
- [X ] I have commented my …

Disable `resolvconf` for `unbound` (optional)

---

docs/abbreviations.md
docs/guides/wireguard/client.md
docs/guides/wireguard/concept.md
docs/guides/wireguard/faq.md
docs/guides/wireguard/internal.md
docs/guides/wireguard/overview.md
docs/guides/wireguard/route-everything.md
docs/guides/wireguard/server.md
mkdocs.yml

You may ask: Why another guide when there are already quite a few on the web?
The answer is manifold:
1. The vast majority of online guides only sets up an IPv4 tunnel. **The Pi-hole guide gives you IPv4 and IPv6 through the same tunnel.**
2. This guide is **build around a DNS server being in the center of the tunnel**. This ensures the settings are fine-tuned so no DNS leakage happens.
3. Some guides show you how to make your internal network clients available through the tunnel, sometimes, they tell you how to route your entire traffic over the Internet. **In our guide, we show you all the options and you decide exactly what you want**. Everything in one place means a similar writing style and expectation on what you did before. This makes it easier for you to set things up.
4. The …

Add official Pi-hole WireGuard guide

---

docs/guides/dns/cloudflared.md

The cron.weekly scripts are started by run-parts which skips all files with extension.
https://serverfault.com/questions/408093/why-does-cron-weekly-not-run
*not applicable for the documentation update*
*not applicable for the documentation update*
---
*Fix the issue in the documentation. Cron doesn't run scripts with extension in file name (https://serverfault.com/questions/408093/why-does-cron-weekly-not-run)*
**How does this …

removed script extension (.sh) for the cron files

---

docs/ftldns/compile.md

---
From the `nettle-3.7.2` CHANGELOG:
This is a bugfix release, fixing a bug in ECDSA signature
verification that could lead to a denial of service attack
(via an assertion failure) or possibly incorrect results. It
also fixes a few related problems where scalars are required
to be canonically reduced modulo the ECC group order, but in
fact may be slightly larger.
>>> Upgrading to the new version is strongly recommended. <<<
Even when no assert is triggered in ecdsa_verify, ECC point
multiplication may get invalid intermediate values as input,
and produce incorrect results. It's trivial to construct
alleged signatures that result in invalid intermediate values.
It appears difficult …

Recommend to use nettle 3.7.2

---

docs/extra.css
mkdocs.yml

---
- Show back-to-top button when the user, after scrolling down, starts to scroll up again. It's rendered in the lower right corner of the view port.
- Add dark mode switch (check out the lightbulb in the header)
For proper color support we need CSS variables, however, I think they are safe to use concerning [browser support](https://caniuse.com/css-variables) (we don't want to support IE IIRC).

Add scroll-up and dark mode to documentation

---

docs/ftldns/configfile.md

---
Inform the user that `MAXLOGAGE` values greater than 24 can be set by compiling FTL manually

MAXLOGAGE >24h need a locally compiled FTL

---

docs/ftldns/configfile.md

---
Adds the debug flag `DEBUG_EDNS0`

Add EDNS0 debug info

---

docs/ftldns/configfile.md

---
Simply fixing the double TOC label

Fix TOC label

---

docs/ftldns/configfile.md

---
The default value of `REPLY_WHEN_BUSY` is to allow the queries. 
https://github.com/pi-hole/FTL/blob/db8ee8c6ac88c61c9ea160cce3fa4a84ca30ce5b/src/config.c#L584
This PR changes the documentation accordingly.

Change default order of options for REPLY_WHEN_BUSY

---

docs/docker/DHCP.md
docs/guides/vpn/openvpn/client.ovpn
docs/main/origins.md

Signed-off-by: David Beitey <david@davidjb.com>
---
Improve security in external links mentioned in documentation and guides.
Updates `http://` URLs to use `https://`; each URL has been tested and loads appropriately.
None that I'm aware of; the links are the same, just more secure.

Use https for URLs in docs and guides

---

docs/guides/vpn/wireguard/client.md

Removed the server config line "SaveConfig = true". This one does only
appear in the add client section.
---
Adding the the config line `SaveConfig=true` enables WireGuard to save the configuration of an interface on exit.
The problem is that if you are following the guide, restarting WireGuard overwrites your config changes.
Another point is that this line only exists in the guide for adding a client and not for setting up the server.
According to some forum and reddit threads this is a problem.
Remove the offending line …

Fix wireguard guide

---

docs/guides/vpn/wireguard/client.md

---
The existing "all commands you need to run" box is replaced by a proper script that makes adding new Wireguard clients easier than it ever was (a single line you have to run). Tested on two independent servers and with Android and Linux clients.
In addition, this fixes a few shortcomings I discovered only today: the existing hints are not sufficient and can cause frustration because clients cannot connect.

Add script for automated Wireguard client generation

---

docs/extra.css
mkdocs.yml

---
Fixes the styling of `pihole` in the sidebar.
Before:
After:
How?
Material for MKDocs automatically sets `display` to `flex` for `.md-nav__link`
https://github.com/squidfunk/mkdocs-material/blob/05440550509097f81cec8274c461fe29b0c12a95/src/assets/stylesheets/main/layout/_nav.scss#L98
This does not play well with the `<samp>` we use here to emphasize `pihole`. Changing it to `inline-flex` works better, but need two `&nbsp` to get some space around the `<samp>`

Fix ugly 'pihole' styling

---

docs/ftldns/configfile.md

---
Minor addition. Adds `HOSTNAMEFQDN` to `PIHOLE_PTR=` heading

Add HOSTNAMEFQDN to PIHOLE_PTR heading

---

docs/ftldns/dnsmasq_warn.md

---
Extend description of a few `dnsmasq` warnings by what causes them and how to fix them. I expect such extensions of the description to happen a few times. I still seems worthwhile to push the updates as soon as we have them (similar to the FAQ section) as it may help users helping themselves.

Extend some dnsmasq warning descriptions

---

docs/ftldns/dnsmasq_warn.md
docs/guides/dns/unbound.md

---
Update suggested EDNS buffer size to 1232 as recommended on DNS Flag Day 2020. There is more reasoning given in the `unbound` config comment added within this PR.

Update suggested EDNS buffer size to 1232

---

docs/ftldns/configfile.md

Adds a note on the comment syntax of pihole-FTL.conf
See this discussion: https://github.com/pi-hole/pi-hole/pull/4081

Add note how to add comments to pihole-FTL.conf

---

docs/guides/vpn/wireguard/internal.md

---
Debian 11/Raspian 11 doesn't inlcude iptables per default, so for the NAT we need to install it. It translates automatically the commands to nftables. Only the PostDown command doesn't work on iptables base. Maybe there is another way to remove the exact line from nftables. The configuration is tested on a fresh raspian 11.
Installing iptables, modifing configuration
**What documentation changes (if any) are …

Include configuration for Debian Bullseye NAT

---

docs/ftldns/telnet-api.md

---
Documents the new `dns-port` telnet API endpoint added in https://github.com/pi-hole/FTL/pull/1264

Add dns-port to telnet documentation

---

docs/ftldns/blockingmode.md

---
Add deprecation note to the IP blocking modes. The blocking page is not accessible via `https` web pages - which are the majority of pages on the internet today (except if you have a MTM setup). Those options should be considered deprecated as they will be removed in a future Pi-hole version.

Add deprecation note to IP blocking mode

---

docs/main/post-install.md

---
Adds a note how to the post install documentation about how to use Pi-hole with the device hosting it. And a big warning why one might not do it.

Add note to post-install about how to use Pi-hole by host device

---

docs/database/ftl.md

---
Add changes introduced in https://github.com/pi-hole/FTL/pull/1285. This PR is meant to come on top of #645 and, hence, is based on its branch. The only real difference is in https://github.com/pi-hole/docs/commit/dbf671de8dd997d2282107a69da73b20bb6be80d

Add documentation for FTL#1285

---

docs/guides/vpn/wireguard/client.md
docs/guides/vpn/wireguard/internal.md

Signed-off-by: Max Steele <max@amaxsteele.com>
---
Most of the guide for using Wireguard uses the IPv6 prefix of fd08:4711::/64, but a few places use fd08::/64. This could cause some strange behavior depending on how the server-side network is configured. At the very least, it is confusing to those who don't understand what these commands mean. I have checked and there are no related issues.
In the Wireguard VPN …

Fix Inconsistency of IPv6 Addresses

---

requirements.txt

See: https://github.com/mkdocs/mkdocs/issues/2799
Not sure if the bump to mkdocs 1.3.0 will cause issues - if it does we can use 1.2.4 instead

Upgrade mkdocs/material to fix Netlify breakages

---

docs/guides/vpn/wireguard/internal.md

Signed-off-by: CleanMachine1 <78213164+CleanMachine1@users.noreply.github.com>
---
Fixing a dependency issue which will cause wireguard not to function if nftables is not installed. (I discovered this on my upgraded from buster to bullseye install by going through the journalctl logs)
**What documentation changes …

Add requirement of nftables to wireguard config

---

docs/guides/vpn/wireguard/client.md

---
Fix the automatic script in Wireguard DNS guide for automatically generating client configs. It does not work without specifying the DNS for obvious reasons.
Add the missing DNS. It is there in the manual steps but was missing in the script.
This is a documentation change.
---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

Specifying DNS Server for client config in automatic script.

---

docs/guides/vpn/wireguard/client.md

---
In the Pi-hole guide for [Wireguard VPN Client configuration](https://docs.pi-hole.net/guides/vpn/wireguard/client/), in the automatic script section, it says to run `umask 077` under `sudo -i` and then run the script.
This does not work, and this error is spit out along with the QR Code:
```
Warning: writing to world accessible file.
Consider setting the umask to 077 and trying again.
```
If 'umask 077' is added to the script itself, it does work and no error is spit.
This also leads to less commands for the user to copy and paste.

Fixing the umask operation by transferring it to the script itself.

---

docs/guides/webserver/caddy.md

---
I use Caddy as my main web server with Pi-hole, when i update pi-hole `pihole -up`.the lighttpd fail to start, because lighttpd config file changes lost on the update. so i need change the `external.conf` not `lighttpd.conf`.
edit `external.conf` to change the server port.
from here: https://raspberrypi.stackexchange.com/questions/52090/how-do-i-change-pi-holes-url-path/117849#117849
**What documentation …

when update, the lighttpd config file changes will lost，use other config file to avoid this happen

---

docs/guides/vpn/wireguard/client.md

---
The command to run the Wireguard client generation script is not correct.
It asks the user to give bash the path to script as the first argument.

Fix the command to run the Wireguard client generation script

---

docs/guides/dns/cloudflared.md

---
Fixes https://github.com/pi-hole/docs/issues/710. The workaround link to older `cloudflared` version (introduced by https://github.com/pi-hole/docs/pull/475) does not exist anymore.

Remove workaround link for cloudflared on arm32 devices

---

docs/ftldns/telnet-api.md

Documentation for FTL's API `>gateway` endpoint added by https://github.com/pi-hole/FTL/pull/1354

Add >gateway endpoint

---

docs/regex/tutorial.md

The section on character groups clearly states "To include a literal
-, make it the first or last character, ..."
In the example `Block domains without subdomains` the bounded
character group `[\-]{1}` should be `[-]{1}` if the intention is to match a
literal `-` as suggested by the accompanying description.
--- …

Fix error in 'Advanced examples' expression

---

docs/database/ftl.md

Adds missing status types added by https://github.com/pi-hole/FTL/pull/1156 and https://github.com/pi-hole/FTL/pull/1338

Add missing status types

---

docs/ftldns/configfile.md

Documentation changes for https://github.com/pi-hole/FTL/pull/1349.
`DELAY_STARTUP` now only takes effect within the first 60 seconds after system boot. This prevents delays if the system is running for a longer time and FTL is restarted

Only DELAY_STARTUP within 60sec after boot

---

docs/ftldns/configfile.md

Adjusts the documentation to reflect changes in https://github.com/pi-hole/FTL/pull/1341

Change default REPLY_WHEN_BUSY to drop

---

.github/workflows/calibreapp-image-actions.yml
.github/workflows/ci.yml
.github/workflows/codespell.yml

Same as https://github.com/pi-hole/pi-hole/pull/4833
---
---

Explicit set minor and patch version on used actions

---

docs/guides/dns/cloudflared.md

Fixes: https://github.com/pi-hole/docs/issues/761
If the old binaries were not removed after downloading, the update `wget` command will append a number to the new downloaded file and the old file will be copied.
Instead of copying, we move the file. No old files will remain for the next update
---
3. I am willing to help maintain this change …

Move downloaded cloudflared binaries instead of copying

---

docs/main/prerequisites.md

To be merged after the following PR has made it to the master branch in core:
https://github.com/pi-hole/pi-hole/pull/4828

Remove CentOS 7 from list of supported OS

---

docs/core/pihole-command.md

Regex and Wildcard use a double dash "--" rather than a single dash "-"
Signed-off-by: Noah Nash <48302704+noah-nash@users.noreply.github.com>
---
The documentation page has a small syntax error. This PR fixes it
Added in the missing dash `-` character to the relevant …

Fix Regex and Wildcard commands

---

docs/main/prerequisites.md

Drops Fedora 34 from the list of supported OS and adds Fedora 35 and Fedora 36. 
Accompanies: https://github.com/pi-hole/pi-hole/pull/4952
--- …

Drop Fedora 34 and add 35 & 36

---

docs/ftldns/configfile.md

FTL PR https://github.com/pi-hole/FTL/pull/1445 removes the `PORTFILE` config option as we read the API port now directly from `pihole-FTL.conf` in `web` and `core`. This marks the `PORTFILE` option as deprecated
---
5. I …

`PORTFILE` is deprecated

---

docs/guides/dns/unbound.md

Use `dnssec.works` instead of `verteiltesysteme.net` in our unbound documentation (see https://github.com/pi-hole/FTL/pull/1469#issuecomment-1307718167 for further details).
---
5. I have squashed any insignificant commits. …

use dnssec.works instead of verteiltesysteme.net in unbound documentation

---

docs/routers/fritzbox-de.md
docs/routers/fritzbox.md

Extend FritzBox guide: 
1. make DNS a realtime-service. This assigns priority when the connection is completely used, e.g. by a running download and,
2. add filter (= firewall) instructions to block port 53/UDP for devices in your local network except the Pi-hole
---
5. It is compatible with the [EUPL 1.2 …

Fritz!Box: assign DNS real-time priority and block bypassing DNS traffic

---

docs/ftldns/valgrind.md

Improve `valgrind` guide. Using the `--log-file` options instead of piping the command itself is able to also catch all the forked child processes.
--- …

Tweaks for the valgrind guide

---

docs/guides/dns/unbound.md

Fix `unbound` guide concerning the optional query/debug logging. The guide was accurate for older versions, however, `unbound` received rather strict `apparmor` rules recently preventing it from creating any file besides the default ones without a proper exception. This prevents `unbound` from creating the manually added log files.
See https://discourse.pi-hole.net/t/unbound-not-working-even-with-extra-steps/60117/10 for details.
---
2. I have commented my proposed changes …

Unbound guide: Add AppArmor instructions for logging

---

docs/guides/vpn/wireguard/internal.md
docs/guides/vpn/wireguard/server.md

`ntftables` is by now the preferred method. It also has the benefit that we do not need to hard-code an interface. In this case, `nftables` can identify the correct interface to forward the packets to (typically the Internet) solely by looking at the kernel's routing table
---
4. It is compatible with the [EUPL …

Wireguard: nftables preferable over iptables

---

docs/database/ftl.md
docs/regex/pi-hole.md

Document support of comma-separated query types in the regex extension `;querytype=A,AAAA.` Furthermore, be a bit more explicit about what OTHER means in which context.
Fixes #851 
---
5. I have squashed any insignificant …

;querytype=... list support

---

docs/guides/dns/unbound.md

Tweaks the instruction on how to disable `resolvconf.conf` entry for unbound based on https://discourse.pi-hole.net/t/warning-raspbian-october-2021-release-bullseye-unbound/51027/53?u=yubiuser
---
5. I have squashed any …

Tweak unbound instruction

---

.github/dependabot.yml

Keep v6 branch dependencies up-to-date with `master
---
6. I have checked that …

Run dependabot on v6 branch

---

docs/ftldns/telnet-api.md

Removes outdated Telnet API endpoint from the docs. Fixes https://github.com/pi-hole/docs/issues/913
https://github.com/pi-hole/FTL/commit/3a4d8e2 removed the `>domain` endpoint.
---
5. I have squashed any insignificant …

Remove >domain from Telnet API

---

docs/database/ftl.md

Documentation change accompanying https://github.com/pi-hole/FTL/pull/1607
**Related issue or feature (if applicable):** This is the docs change
---
5. I have squashed any insignificant …

Add regex_id field of the query table

---

docs/abbreviations.md
docs/api/auth.md
docs/api/index.md
mkdocs.yml

See title. This is basically an extended version of [my comment on Discourse](https://discourse.pi-hole.net/t/authenticating-to-v6-api/66010/6?u=dl6er).
--- …

Add authentication documentation

---

docs/guides/vpn/openvpn/android-client.md
docs/guides/vpn/openvpn/clients.md
docs/guides/vpn/openvpn/deprecation_notice.md
docs/guides/vpn/openvpn/dual-VPN.md
docs/guides/vpn/openvpn/dual-operation.md
docs/guides/vpn/openvpn/dynDNS.md
docs/guides/vpn/openvpn/firewall.md
docs/guides/vpn/openvpn/installation.md
docs/guides/vpn/openvpn/only-dns-via-vpn.md
docs/guides/vpn/openvpn/overview.md
docs/guides/vpn/openvpn/setup-openvpn-server.md
docs/guides/vpn/openvpn/troubleshooting.md
mkdocs.yml
requirements.txt

Add notice to each OpenVPN page:
--- …

Add deprecation notice to OpenVPN pages

---

docs/ftldns/compile.md

This change accompanies https://github.com/pi-hole/FTL/pull/1765. The packages are:
- https://packages.ubuntu.com/jammy/libidn2-dev
- https://packages.ubuntu.com/jammy/libunistring-dev
- https://packages.fedoraproject.org/pkgs/libidn2/libidn2-devel/
- https://packages.fedoraproject.org/pkgs/libunistring/libunistring-devel/
---
2. I have commented my proposed changes …

Update dependencies due to switching from libidn -> libidn2

---

docs/guides/dns/unbound.md

Just a quick fix for a typo in the instructions for setting up AppArmor with unbound and pi-hole.

Small typo in setup for unbound with pi-hole and AppArmor

---

docs/ftldns/debugging.md

Improve the debugging command.
---
6. I have checked that another pull request for …

Use PID file instead of pidof output for gdb debugging

---

docs/main/prerequisites.md

This is the documentation change for https://github.com/pi-hole/pi-hole/pull/5111.
--- …

We don't offer setting a static IP anymore

---

docs/docker/build-image.md
mkdocs.yml

Adds a slightly more fleshed out version of the instructions on the V6 readme. Includes some examples for users who are asked to checkout alternative branches
--- …

Add some information about building the docker image locally

---

docs/docker/build-image.md
docs/docker/configuration.md
docs/docker/index.md
docs/docker/upgrading/index.md
docs/docker/upgrading/v5-v6.md
mkdocs.yml

WIP: Probably needs some polish and proof reading!
---
---

Add Some more detailed Docker documentation

---

docs/main/prerequisites.md

See title. Idee brought up [here](https://github.com/pi-hole/docs/pull/984#pullrequestreview-2327357725).
As an alternative to https://github.com/pi-hole/docs/pull/984
This will save us from updating the list every time a new OS is released.
--- …

Remove version and architecture info from supported OS list

---

docs/guides/dns/cloudflared.md

Add a step if cloudflared runs on different machine
4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation …

Update cloudflared.md for installation on different machine

---

docs/guides/dns/unbound.md

Remove recommendation to manually configured `edns-packet-max=1232`. This is the default in dnsmasq for almost two years now, both in `development` as well as in `master` as of [FTL v5.22](https://github.com/pi-hole/FTL/releases/tag/v5.22) (March 2023).
Related commit from 2023: https://github.com/pi-hole/FTL/commit/e5c5a34dd772d1b421fc95e4195c0e2c88f5294d
**edit** Related Discourse thread: https://discourse.pi-hole.net/t/etc-pihole-pihole-toml-makes-me-very-happy/75660/3
---
1. I have read and understood the [contributors …

unbound guide: Remove edns-packet-max recommendation

---

docs/guides/dns/unbound.md

Enable IPv6 in Unbound config by default

---

docs/regex/tutorial.md

Clarify how character classes need to be specified and explain how they can be combined with other selectors in character groups.
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2364
--- …

Improve regex documentation

---

.devcontainer/devcontainer.json
docs/docker/configuration.md

Companion/folllowup to https://github.com/pi-hole/docker-pi-hole/pull/1778
includes an extra commit that makes the devcontainer usable on Mac - minor tweak, no sense in doing a whole PR for it - it has the same logic as https://github.com/pi-hole/FTL/pull/2152
--- …

Be explicit about setting a blank password in docker

---

docs/guides/dns/unbound.md

Adding the remaining zones from RFC6303 section 4.2 - 4.6 prevents reverse dns lookups from being sent in the event of a misconfigured or malicious device on the network. This is best practice for recursive dns resolvers.
Adds the remaining zones from RFC6303 section 4.2 - 4.6 
(The other zones are already either specified within unbound, or within the file)
---
2. I have commented my proposed changes within the code and I have …

Prevent reverse dns requests from non-routable zones. (RFC6303 4.2)

---

README.md
docs/abbreviations.md
docs/ftldns/dnsmasq_warn.md
docs/guides/vpn/openvpn/dynDNS.md

Fixes a few typos in the docs
---
6. I have checked that another pull request for …

Fix typos in docs

---

.github/workflows/ci.yml
package.json

Now CI runs build once.
~~Draft until #1194 is sorted.~~
4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation …

Tweak npm scripts

---

docs/ftldns/signals.md

After a report on Discourse, investigations have revealed that `SIGRTMIN` are defined differently in Debian (glibc-based) and Alpine (musl-based). Hence, sending signals relative to `SIGRTMIN` is going to be an issue on Debian as we build the pihole-FTL binaries on Alpine. Change the documentation to use fixed signals (instead of relative ones) to fix this. Signals relative to the constant `SIGRTMIN` have been added as there is a certain number ambiguity under `glibc` (see man 7 signals). However, this ambiguity does not exist in `musl`-based binaries.
1. Base your code and PRs against the …

Clarify signal documentation

---

docs/main/prerequisites.md

Deletes the references to the old API port 4711 from the docs
---
6. I have checked …

Remove references to old API port 4711

---

docs/guides/vpn/wireguard/client.md

Serveur config: correct IPv6 range discrepancy between client.md and server.md
In the documentation, there is a discrepancy in the IPv6 address in the server config show in server.md and client.md.
- server.md server config:
> [Interface]
> Address = 10.100.0.1/24, fd08:4711::1/**64**
- Original client.md server config:
> [Interface]
> Address = 10.100.0.1/24, fd08:4711::1/**128**
The mistake seems to be on client.md: "/128" should be "/64."
It corrects the wrong IPv6 range in the documentation.
N/A
---
1. I have read and understood the [contributors …

Update client.md, correct IPv6 range discrepancy with server.md

---

docs/main/post-install.md

Amends the post-installation documentation on how to add the local user to the 'pihole' group. This is necessary to access `/etc/pihole` and allow to read the version file as well as `cli_pw` for non-password CLI authenticatin.
Accompanies: https://github.com/pi-hole/pi-hole/pull/6152
---
4. It is compatible with …

Add info how to add local user to pihole group

---

docs/main/pihole-command.md

Removing an example usage command-line flag that does nothing from the documentation.
Changes the documentation
--- …

Removed unavaliable command-line flag documentation

---

docs/guides/dns/unbound.md

Document solution for `so-rcvbuf 1048576 was not granted` warning that commonly appears in unbound logs.
Adds a step-by-step troubleshooting section to the unbound guide that explains how to resolve the warning message
n/a
---
3. I am willing to help maintain this change if there are …

Add unbound `rcvbuf` warning troubleshooting documentation
